giantswarm/gsctl

- commands/commands.go
- commands/create.go
- commands/list.go
- commands/login.go
- commands/logout.go
- commands/ping.go
- commands/root.go
- config/config.go
This PR makes the GS API endpoint configurable. 
RFR @JosephSalisbury @marians
> added api endpoint flag

- commands/logout.go
This change ensures that a `gsctl logout` deletes any locally stored credentials.
The former flow would exit before the config file was written in case the API call failed (due to an expired token, for example).
> Ensure deleting of persisted token/email

- glide.lock
- glide.yaml
- vendor/github.com/giantswarm/gsclientgen/docs/V4NodeDefinitionResponseMemory.md
- vendor/github.com/giantswarm/gsclientgen/docs/V4NodeDefinitionResponseStorage.md
- vendor/github.com/giantswarm/gsclientgen/v4_node_definition_response_memory.go
- vendor/github.com/giantswarm/gsclientgen/v4_node_definition_response_storage.go
Fixes https://github.com/giantswarm/gsctl/issues/43
> Switching to latest gsclientgen version

- README.md
- commands/create_kubeconfig.go
Fixes https://github.com/giantswarm/gsctl/issues/61
> Replacing set-context with use-context

- util/datetime.go
- util/datetime_test.go
See https://github.com/giantswarm/gsctl/issues/10
> Support parsing date format with offset

- commands/create_cluster.go
- commands/create_cluster_test.go
- commands/testdata/complete.yaml
- commands/testdata/complete_aws.yaml
Part of the long-running quest to have good unit test coverage in gsctl.
> Adding tests for cluster creation

- README.md
- Changed column headers to uppercase
- Added "UTC" indicator to create date
> Modified "gsctl list clusters" output shown in README

- DEVELOPMENT.md
- README.md
- Moved development topic out of README.md into DEVELOPMENT.md
- Changed Dev docs slighty, added Conventions section
> Better development docs

- Makefile
- update-scoop.sh
Towards https://github.com/giantswarm/giantswarm/issues/1898
> Automation to create scoop manifest

- commands/info.go
> Bugfix for #126

- .gitignore
- commands/completion.go
- commands/create_cluster.go
- commands/create_keypair.go
- commands/create_kubeconfig.go
- commands/delete_cluster.go
- commands/list_keypairs.go
For https://github.com/giantswarm/gsctl/issues/149
See `gsctl completion -h` for details.
TODO
> Command to generate bash/zsh completion files

- docs/Release.md
To avoid issues in happa or docs
> Avoid trailing newline in VERSION

- commands/create_cluster.go
- commands/error.go
We can merge this as soon as https://github.com/giantswarm/api/pull/490 got merged.
> don't validate the release version in the client

- commands/error.go
- commands/list_releases.go
- commands/list_releases_test.go
Fixes https://github.com/giantswarm/gsctl/issues/182
> Sort releases by version number

- commands/show_cluster.go
- commands/show_cluster_test.go
Handle error cases where API returns non-OK HTTP error code:
- HTTP 401 Unauthorized
- Probably doesn't occure often in the real life as login has failed
beforehand, but in case it happens, handle this gracefully with
meaningful error message.
- HTTP 404 Not Found
- If non-existing cluster id is given for `show cluster`, handle API
response gracefully and give meaningful error message.
- HTTP 500 Internal Server Error
- When all hope is lost, try to still behave sensibly for the end
user. It's the API that has something wrong, not `gsctl`.
While here, also added check to showClusterRunOutput that checks length
of the Workers slice before addressing the first element. Earlier this
gave "index out of range" error especially when API errors were not
handled. Now it behaves gracefully.
> Improve `show cluster` error handling

- Gopkg.lock
- Gopkg.toml
- commands/commands.go
- commands/create_cluster.go
- commands/show_cluster.go
- vendor/github.com/giantswarm/gsclientgen/api-spec/oai-spec.yaml
- vendor/github.com/giantswarm/gsclientgen/docs/V4ModifyClusterRequest.md
- vendor/github.com/giantswarm/gsclientgen/docs/V4NodeDefinition.md
- vendor/github.com/giantswarm/gsclientgen/docs/V4NodeDefinitionAzure.md
- vendor/github.com/giantswarm/gsclientgen/docs/V4NodeDefinitionResponse.md
- vendor/github.com/giantswarm/gsclientgen/v4_node_definition.go
- vendor/github.com/giantswarm/gsclientgen/v4_node_definition_azure.go
- vendor/github.com/giantswarm/gsclientgen/v4_node_definition_response.go
Provide the new `--azure-vm-size` to `gsctl create cluster`
Show `Worker vm size: <vm size>` on `gsctl show cluster`
Require: https://github.com/giantswarm/gsclientgen/pull/24
> Add Azure vm_size support

- .circleci/config.yml
- Makefile
Making the switch to Golang 1.10
> Set go version to 1.10

- commands/error.go
- commands/login.go
- commands/login_test.go
Fixes https://github.com/giantswarm/gsctl/issues/203
> Handle inactive account

- Makefile
I'll merge this as there is hardly a thing to review.
> Add prerequisite to 'make test'

- commands/create_cluster.go
- commands/create_kubeconfig.go
Towards https://github.com/giantswarm/gsctl/issues/198
> Add an extra comment when cluster is created warning about the orgs flag

- commands/create_kubeconfig.go
- commands/create_kubeconfig_test.go
Closes https://github.com/giantswarm/gsctl/issues/244
> Fix nil pointer panic in 'gsctl create kubeconfig'

- commands/login_giantswarm.go
- commands/login_sso.go
Fixes https://github.com/giantswarm/giantswarm/issues/3648
> Fix endpoint select on SSO login

- client/client.go
- client/clienterror/clienterror.go
- client/legacy.go
- commands/list_clusters.go
- commands/list_clusters_test.go
- config/config.go
> Migrate 'list clusters' command to new client

- client/client.go
This eliminates the need for nil checks in all wrapper functions.
> Modify wrapper receiver, remove checks for receiver being nil

- client/client.go
Merged it and then remembered that you pointed this out to me @marians.
> Don't set params with authorization here

- Gopkg.lock
- commands/commands.go
- commands/login.go
- commands/login_sso.go
- config/config.go
- oidc/callback_server.go
- oidc/error.go
- oidc/jwt.go
- oidc/pkce.go
- oidc/refresh_token.go
- vendor/github.com/giantswarm/microerror/error.go
- vendor/github.com/giantswarm/microerror/spec.go
- vendor/github.com/giantswarm/microerror/string_case.go
This PR implements the final step of the refresh token story.
It checks if the token we're about to use is valid. If it isn't it'll perform the steps needed to get a new one using the stored refresh token.
Towards: https://github.com/giantswarm/giantswarm/issues/2480
> Validate and renew access token if needed.

- .circleci/config.yml
- .circleci/release.sh
Towards https://github.com/giantswarm/giantswarm/issues/4810
- Should fix the asset upload
- disables updating of scoop and homebrew (want to verify the release is working first)
- better log output
> Refine release script

- commands/error.go
- commands/scale_cluster.go
Now we can have much more flat error checking.
> Check for individual errors explicitly

- client/clienterror/clienterror.go
This adds handling of errors that can occur in cluster modification, to prevent output like this:
```
Unknown error: [PATCH /v4/clusters/{cluster_id}/][500] modifyCluster default  &{Code:INTERNAL_ERROR Message:An unexpected error occurred. Sorry for the inconvenience.}
An error has occurred for which we don't have specific handling in place.
Please report this error to support@giantswarm.io including the command you
tried executing and the context information (gsctl info). Details:
&clusters.ModifyClusterDefault{_statusCode:500, Payload:(*models.V4GenericResponse)(0xc0001de0c0)}
```
> Add specific error handling for cluster modification

- commands/scale_cluster.go
Towards spec https://github.com/giantswarm/giantswarm/issues/5037#issuecomment-459738845
I changes the messages a little bit and made them individual for pinned vs not pinned. I thought that was easier to understand.
> Adapt confirmation messages

- commands/scale_cluster.go
Use actual worker count for confirmation instead of desired count.
> Use current workers count for confirmation instead of desired

- commands/root_test.go
In a general attempt to increase the test coverage
> Add test for root command

- commands/completion.go
- commands/root.go
This changes the way the completion command is added to be more like the other commands. Ideally it would be a sub package, but that's another step.
> Align adding of completion command

- commands/root.go
This activates the ping command again which got deactivated accidentally
> Re-enable ping command

- .circleci/config.yml
This pulls changes from https://github.com/giantswarm/gsctl/pull/381 to merge them right away
> Improve CircleCI config

- commands/create/cluster/command.go
- commands/create/cluster/command_test.go
> Alignment of arguments use in 'create cluster'

- commands/create/keypair/command.go
- commands/create/keypair/command_test.go
> Alignment of arguments use in 'create keypair'

- commands/create/kubeconfig/command.go
- commands/create/kubeconfig/command_test.go
> Alignment of arguments use in 'create kubeconfig'

- commands/delete/cluster/command.go
- commands/delete/cluster/command_test.go
- commands/info/command.go
- commands/info/command_test.go
This accidentally combines the changes on two commands.
>  Alignment of arguments use in 'delete cluster' and 'info'

- commands/list/clusters/command.go
- commands/list/clusters/command_test.go
> Alignment of arguments use in 'list clusters'

- commands/list/endpoints/command.go
- commands/list/endpoints/command_test.go
> Alignment of arguments use in 'list endpoints'

- commands/list/keypairs/command.go
- commands/list/keypairs/command_test.go
> Alignment of arguments use in 'list keypairs'

- commands/list/nodepools/command.go
- commands/list/nodepools/command_test.go
> Alignment of arguments use in 'list nodepools'

- commands/upgrade/cluster/command.go
- commands/upgrade/cluster/command_test.go
> Alignment of arguments use in 'upgrade cluster'

- commands/update/organization/setcredentials/command.go
- commands/update/organization/setcredentials/command_test.go
> Alignment of arguments use in 'update org'

- commands/show/release/command.go
- commands/show/release/command_test.go
> Alignment of arguments use in 'show release'

- commands/show/nodepool/command.go
- commands/show/nodepool/command_test.go
> Alignment of arguments use in 'show nodepool'

- commands/scale/cluster/command.go
- commands/scale/cluster/command_test.go
> Alignment of arguments use in 'scale cluster'

- commands/ping/command_test.go
> Alignment of arguments use in 'ping'

- commands/show/cluster/command.go
- commands/show/cluster/command_test.go
> Alignment of arguments use in 'show cluster'

- commands/logout/command.go
- commands/logout/command_test.go
>  Alignment of arguments use in 'logout'

- commands/login/command.go
- commands/login/command_test.go
- commands/login/giantswarm_theme.go
- commands/login/sso.go
> Alignment of arguments use in 'login'

- commands/list/releases/command.go
- commands/list/releases/command_test.go
> Alignment of arguments use in 'list releases'

- commands/list/organizations/command.go
- commands/list/organizations/command_test.go
> Alignment of arguments use in 'list organizations'

- commands/create/cluster/command.go
The flag has been removed already some time ago, but this line was forgotten.
> Remove obsolete flag deprecation

- commands/create/cluster/command.go
- commands/create/cluster/command_test.go
This PR adjusts the argument naming in the `create cluster` command to enable deep diffs in tests in a next step and for general alignment.
> Rename and expose arguments in 'create cluster'

- commands/create/cluster/command.go
Extracting two things here to make upcoming PRs on this command simpler:
- return (nil, error) instead of an (someStruct{}, error) from all functions in error case
- split `readDefinitionFromFile` into one function parsing YAML and one reading files, as we are going to support YAML from STDIN.
> Boyscouting in 'create cluster'

- commands/show/cluster/command.go
- commands/show/cluster/command_test.go
Just some renaming to match our conventions
> Rename verifyShowClusterPreconditions -> verifyPreconditions

- commands/delete/nodepool/command.go
- commands/delete/nodepool/command_test.go
Fixes https://github.com/giantswarm/giantswarm/issues/8937
> Add error handling for positional argument syntax in 'gsctl delete nodepool'

- commands/login/command.go
Fixes https://github.com/giantswarm/giantswarm/issues/9085
This PR fixes a regression introduced with https://github.com/giantswarm/gsctl/pull/499 that would prevent the email argument from being passed to the API call.
> Fix passing of email argument to login command

- commands/completion.go
Follow-up to https://github.com/giantswarm/gsctl/pull/558
> Improve help formatting and grammar for completion

- commands/show/nodepool/aws.go
- commands/show/nodepool/azure.go
- commands/show/nodepool/command.go
- commands/show/nodepool/command_test.go
Towards https://github.com/giantswarm/giantswarm/issues/12427
Should behave the same as the AWS counterpart, but **without**:
* node pool scaling
* spot instances
Also cleaned up the code a little bit.
> azure v5: show nodepool

- commands/update/nodepool/command.go
- commands/update/nodepool/command_test.go
- go.mod
- go.sum
Towards https://github.com/giantswarm/giantswarm/issues/12535
This PR:
* Supports changing a node pool name (scaling is unsupported at this moment)
<details>
<summary>Command help</summary>
</details>
<details>
<summary>Update name</summary>
</details>
<details>
<summary>Trying to use autoscaling (unsupported right now)</summary>
</details>
<details>
<summary>Trying to update... nothing</summary>
</details>
> azure v5: modify node pool

- commands/create/cluster/read_definition_test.go
- commands/create/cluster/testdata/v5_three_nodepools_azure.yaml
- commands/list/nodepools/command_test.go
- commands/show/nodepool/command_test.go
- nodespec/azure.go
- nodespec/azure_test.go
PR towards: https://github.com/giantswarm/giantswarm/issues/9313
For including GPU instances for Azure as well as removing instances with 2CPUs
> Add Azure GPU/Remove 2 CPU instances

- commands/create/nodepool/command.go
- commands/create/nodepool/command_test.go
Fixes https://github.com/giantswarm/giantswarm/issues/14915
> Default NP creation to no AZs on installations that don't support them

- commands/create/nodepool/command.go
- commands/create/nodepool/command_test.go
- commands/list/nodepools/command.go
- commands/list/nodepools/command_test.go
- commands/show/nodepool/azure.go
- commands/show/nodepool/command_test.go
- commands/update/nodepool/command.go
- commands/update/nodepool/command_test.go
Towards https://github.com/giantswarm/giantswarm/issues/14795
This PR adds node pool autoscaling support for Azure.
> Enable Azure node pool autoscaler

- go.mod
- go.sum
@anvddriesch This was required for me in order to build on Mac OS.
> Update golang.org/x/sys to re-enable darwin builds
