giantswarm/gsctl

Makefile
README.md
commands/commands.go
commands/create.go
commands/info.go
commands/list.go
commands/login.go
commands/logout.go
commands/version.go
config/config.go
main.go

This PR adds two unrelated changes:
Add tracking of user actions ("activities") via request headers, which helps us to understand what users do with the CLI. This submits two request headers to the API:
(1) a request ID, which will also be helpful when debugging requests in the future.
(2) the complete command line. Part (2) can be deactivated using the `GSCTL_DISABLE_CMDLINE_TRACKING` environment variable (see README).
These changes are based on user feedback (thanks @teemow!)
- Colors can now be turned off by setting the environment variable `GSCTL_DISABLE_COLORS`.
- Table output for the commands `gsctl list clusters`, `gsctl list organizations`, and `gsctl list keypairs` has been changed so that only headers are printed in color, while data rows use the default terminal color.
- To …

Add activity tracking, List output optimization and color opt-out, add version command

---

Makefile

- `build` should compile again when sources changed
- `install` should build again when sources changed, and ensure
dependencies

Ensure re-build

---

.travis.yml

We build in go 1.7. Testing 1.6 only takes twice the time and has no additional value.

Removing go 1.6 build

---

commands/create.go

- Replaces `g8m` with `gsctl` in a generated description for `gsctl create kubeconfig`
- Adds a default description for the `gsctl create keypair` command

Fix keypair description

---

.travis.yml
Makefile

This PR switches our build (and Travis tests) to Golang 1.8. For builds, the smaller `golang:1.8-alpine` image is now used instead of the standard one.

Use Go 1.8 for builds

---

Makefile
RELEASE.md
update-homebrew.sh

- `assert-tagged-version` just didn't work
- Removed some `rm -rf build` which deleted the stuff we wanted to
distribute
- Deactivated updating of the README, since we are in a detached branch
- Updated RELEASE.md documentation
[skip ci]

Some fixes to the gsctl release automation

---

README.md

Use HTTPS instead of SSH to clone

---

commands/list.go

Having to type 'organizations' keeps tripping me up, and I really hate it.
This adds support for using a spelling I actually know
e.g:
```
09:47:16 ~/go/src/github.com/giantswarm/gsctl (english-please)
$ ./gsctl --api-endpoint=https://api-aws.giantswarm.io list organisations
ORGANIZATION
giantswarm
joseph
```
the usage is hidden, so I don't think we need to worry about people getting confused - american is still the standard:
```
09:47:55 ~/go/src/github.com/giantswarm/gsctl (english-please)
$ ./gsctl --api-endpoint=https://api-aws.giantswarm.io list --help
Prints a list of the things you have access to
Usage:
gsctl list [command]
Available Commands:
clusters      List clusters
keypairs      List key-pairs for a cluster
organizations List organizations
Global Flags:
--api-endpoint string …
```

Adds support for english spelling of organisations

---

commands/ping.go
commands/ping_test.go

This PR
- ensures that ping requests send the user-agent header
- makes the ping function better testable by separating logic from output handling
- adds a unit test

Ping refactoring, testing, sending user-agent header

---

config/config.go
config/config_test.go

Fixes https://github.com/giantswarm/gsctl/issues/59
In #55 a migration of the configuration directory has been introduced. Unfortunately I forgot to take care of a user's kubectl config file.
This PR here makes the migration also maintain the paths. It does it simply by replacing occurrences of the old path with the new path in the config, not trying to be any more clever than that.

gsctl: Ensure that certificate paths get updated with config dir migration

---

commands/create_kubeconfig_test.go

Solves https://github.com/giantswarm/gsctl/issues/56
This PR ensures that a temporary kubectl config file is used for test purposes.
Additionally, the output written to the kubectl config file is now verified.

gsctl: Don't overwrite the user's kubectl config when running tests

---

commands/create_keypair.go
commands/create_kubeconfig.go

Tiny change that lets us see the keypair TTL as received from the backend, as opposed to printing the requested TTL.

On keypair creation, print resulting TTL instead of requested TTL

---

commands/commands.go
commands/create_cluster.go
commands/delete_cluster.go
commands/delete_cluster_test.go

This adds proper unit tests for the "delete cluster" command. As with "create cluster" before, business logic and result printing are now separate.

Test for "delete cluster"

---

README.md
commands/create.go
commands/create_cluster.go
commands/create_keypair.go
commands/create_kubeconfig.go
commands/list.go
commands/list_keypairs.go
commands/list_keypairs_test.go
commands/list_organizations_test.go

We used "key-pair" in many places in gsctl, while we use "key pair" in docs and happa. Towards a unified naming!

Unified naming for "key pair"

---

commands/info.go
commands/info_test.go

See #79 
Also refactored functions to separate info acquisition from info printing. That should help keep the code more readable and testable in the longer run.

Adding API endpoint output to "gsctl info"

---

commands/list_keypairs_test.go
commands/login.go
commands/login_test.go
commands/logout.go
commands/logout_test.go

This PR solves https://github.com/giantswarm/gsctl/issues/22
```nohighlight
$ ./gsctl login marian@sendung.de
Password for marian@sendung.de:
You are logged in as marian@sendung.de at https://api.giantswarm.io.
$ ./gsctl info
Email:                marian@sendung.de
gsctl version:
gsctl build:
Config path:          /Users/marian/.config/gsctl/config.yaml
kubectl config path:  /Users/marian/.kube/config
$ ./gsctl login marian@giantswarm.io --api-endpoint=https://api-g8s.giantswarm.io
Password for marian@giantswarm.io:
You are logged in as marian@giantswarm.io at https://api-g8s.giantswarm.io.
$ ./gsctl info
Email:                marian@giantswarm.io
gsctl version:
gsctl build:
Config path:          /Users/marian/.config/gsctl/config.yaml
kubectl config path:  /Users/marian/.kube/config
``` …

Login switch account

---

client/client.go
commands/ping.go

Fixes #99 in parts.
This change enables the use of a proxy server if the environment variables `HTTP_PROXY` or `HTTPS_PROXY` are set to a proxy server URL.
I used `mitmdump` (https://mitmproxy.org/) as proxy.
```
mitmdump -b 127.0.0.1 -p 8080 -v
```
gsctl call:
```
HTTPS_PROXY=http://127.0.0.1:8080 GSCTL_CAFILE=~/.mitmproxy/mitmproxy-ca.pem ./gsctl ping
```
mitmdump log:
```
Proxy server listening at http://127.0.0.1:8080
127.0.0.1:61909: clientconnect
127.0.0.1:61909: GET https://api.giantswarm.io/v1/ping
<< 200 OK 5b
127.0.0.1:61909: clientdisconnect
```

Configure client to use proxy if environment variables present

---

commands/list_clusters.go

There was a line break missing at the end of the `gsctl list clusters` output.

Ensure line break after clusters table

---

Makefile

Attempt to fix https://github.com/giantswarm/gsctl/issues/110
Status: work in progress
This PR enables using `gsctl` in a Docker container.
To do that, it enables CGO (`CGO_ENABLED=1`) for C bindings, only for the linux binary.
As a consequence the binary is no longer statically linked. This means it requires glibc around. So it won't work in a plain `alpine` Docker image.
Binary for test purposes: [gsctl.zip](https://github.com/giantswarm/gsctl/files/1183432/gsctl.zip)

Make gsctl work in Docker containers

---

commands/list_clusters.go

When there are no clusters to list, before it was this. 
```
xh3b4sd@osx.local lycangsctl list clusters
xh3b4sd@osx.local
```
Now it is this. 
```
xh3b4sd@osx.local lycangsctl list clusters
xh3b4sd@osx.local
```

do not print empty new line in case no cluster can be listed

---

commands/commands.go
commands/create_keypair.go
commands/create_kubeconfig.go

To conform to conventions and to be consistent, this PR changes two new command line flags to use the dash/minus as a word seperator, instead of the underscore.

Setting "-" as the word separator for flags

---

.gitignore
Makefile
RELEASE.md

Solves https://github.com/giantswarm/giantswarm/issues/1598, partly solves https://github.com/giantswarm/gsctl/issues/98
Changes:
- Update to documentation (RELEASE.md)
- Update to Makefile

Automatically sign binaries during release process

---

Makefile

For the Linux build, we have to change from `golang:1.8-jessie` to `golang:1.9-stretch`, as a jessie image is not available for 1.9

gsctl: Build using go version 1.9

---

commands/list_clusters.go
commands/list_clusters_test.go

Fixes #124
The cluster table is now sorted by ID, then organization. The organization column is moved to the seccond position accordingly, as the expectation seems to be that sort order and position correlate.
Example:
```
ID       ORGANIZATION  NAME                                   CREATED
35e3vfw  acme_dev      That brand new development cluster     2017 Oct 10, 07:24 UTC
h9mqa6z  acme          My dearest production cluster          2017 May 16, 09:30 UTC
jjasn0x  some_org      Abandoned cluster from the early days  2017 Apr 16, 09:30 UTC
xs4sew7  acme          A fairly recent test cluster           2017 Oct 06, 02:24 UTC
```
Before, the ORGANIZATION column has been printed last.

Sort cluster list by ID, then organization

---

commands/list_keypairs.go

Towards https://github.com/giantswarm/giantswarm/issues/2084
The CN is truncated to 24 characters, as it's usually pretty long and totally reaks any layout by wrapping lines.

Add CN and O to "list keypairs" output table

---

Makefile

to make sure that make will execute the go build once a go file has
changed the dependencies needed to be shifted around a bit.
also `make install` should be sufficient enough to trigger the build if
it isn't there.

fix make target dependencies

---

commands/list_clusters.go

Fixes https://github.com/giantswarm/gsctl/issues/128
This increases the timeout for the API request issues by `gsctl list clusters`. Seems like that request can take a while when the user is a member of many organizations.

Tweak to prevent timeouts in 'list clusters'

---

commands/list_endpoints.go

This PR introduces to improvements to the `gsctl list endpoints` output table:
- The selected endpoint is highlighted (when coloured output is active)
- The table is sorted by endpoint URL

Highlight selected endpoint, sort endpoint table

---

glide.yaml

Now that https://github.com/giantswarm/gsclientgen/pull/20 is merged, this has to be fixed back to master.

Fixing branch name

---

commands/show_cluster.go
commands/show_cluster_test.go

Two fixes for the implementation of https://github.com/giantswarm/gsctl/issues/105
- Reverted a late change to  `verifyShowClusterPreconditions` that broke the command line execution
- Added the cluster name field to the details output

Fixes for the "show cluster" command

---

commands/create_kubeconfig.go
commands/create_kubeconfig_test.go
util/error.go
util/kubectl.go

For https://github.com/giantswarm/gsctl/issues/114, based on #162 
The actual purpose of this PR is to add a flag `--context` to let the user set a custom context name when desired.
As a side effect, I had to fix a few old mistakes made in the tests.

gsctl create kubeconfig: adding --context flag

---

config/config.go

Fixes https://github.com/giantswarm/gsctl/issues/87
The problem was that the creation using `file, fileErr := os.Create(ConfigFilePath)` simply did not set any permission.
Since users will now have config files with permission 0644 from current gsctl versions, an additional permission udpdate after each write access to the config file should ensure the correct mode.

Ensure config file mode of 0600

---

commands/create_keypair.go
commands/create_kubeconfig.go
util/duration.go
util/duration_test.go

Fixes https://github.com/giantswarm/gsctl/issues/24, based on https://github.com/giantswarm/gsctl/pull/161
Also 
- aligns the output of `create kubeconfig` and `create keypair`.
- removes the output of line `Creating new key pair…`

Human-friendly duration output for key pair expiry

---

commands/create_kubeconfig.go

This fixes a problem where, despite the user setting `--context` in `gsctl create kubeconfig`, the default context name was presented. Quite confusing.

Give the right context in output after creating kubeconfig

---

commands/logout.go

```
$ /opt/bin/gsctl login joseph@giantswarm.io -e [REDACTED]
Password for joseph@giantswarm.io on [REDACTED]: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7791a4]
goroutine 1 [running]:
github.com/giantswarm/gsctl/commands.logout(0xc42011c280, 0x31, 0xc420080210, 0x24, 0xc4200762a0, 0x58)
/go/src/github.com/giantswarm/gsctl/commands/logout.go:115 +0x1f4
github.com/giantswarm/gsctl/commands.login(0xc42011c280, 0x31, 0x7ffedc7366dc, 0x14, 0xc42011c240, 0x40, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/giantswarm/gsctl/commands/login.go:213 +0x88b
github.com/giantswarm/gsctl/commands.loginOutput(0xa9ed00, 0xc42007d8c0, 0x1, 0x3)
/go/src/github.com/giantswarm/gsctl/commands/login.go:151 +0xcd …
```

Fixes panic due to missing check

---

commands/select_endpoint.go

I keep tripping on this (we support plural in `list`, but not select)

Add plural alias for select endpoint

---

commands/create_kubeconfig.go

```
gsctl create kubeconfig --cn-prefix="system:masters" -c 5qufg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x136b248]
goroutine 1 [running]:
github.com/giantswarm/gsctl/commands.createKubeconfig(0xc420012900, 0x33, 0xc42001c3f0, 0x24, 0x7ffeefbff85e, 0x5, 0xc420012c00, 0x40, 0x7ffeefbff84c, 0xe, ...)
/go/src/github.com/giantswarm/gsctl/commands/create_kubeconfig.go:367 +0x1448
github.com/giantswarm/gsctl/commands.createKubeconfigRunOutput(0x1699380, 0xc420075950, 0x0, 0x3)
/go/src/github.com/giantswarm/gsctl/commands/create_kubeconfig.go:272 +0xa2
github.com/giantswarm/gsctl/vendor/github.com/spf13/cobra.(*Command).execute(0x1699380, 0xc4200758c0, 0x3, 0x3, 0x1699380, 0xc4200758c0) …
```

Fix panic if api response is nil

---

commands/commands.go
commands/create_cluster.go
commands/create_cluster_test.go
commands/create_keypair.go
commands/create_keypair_test.go
commands/create_kubeconfig.go
commands/delete_cluster.go
commands/delete_cluster_test.go
commands/error.go
commands/list_clusters.go
commands/list_clusters_test.go
commands/list_keypairs.go
commands/list_releases.go
commands/login.go
commands/logout.go
commands/ping.go
commands/scale_cluster.go
commands/select_endpoint.go
commands/show_cluster.go
docs/Command-Blueprint.md

For https://github.com/giantswarm/gsctl/issues/196
Preview:
```
$ gsctl login dev@example.io
Password for dev@example.io on <endpoint>:
Access Forbidden
The client has been denied access to the API endpoint with an HTTP status of 403.
Please make sure that you are in the right network or VPN. Once that is verified,
check back with Giant Swarm support that your network is permitted access.
```
- `create cluster`
- move out handling of common errors
- handle 403 forbidden error
- `create kubeconfig`
- move out handling of common errors
- handle 403 forbidden error
- `create keypair`
- refactored to match command blueprint, applied structure according to `create kubeconfig`
- applied same client timeout as for `create kubeconfig`
- handle 403 Forbidden error
- `delete cluster`
- move out …

Improve and align error handling, including 404 Forbidden error, in many commands

---

Gopkg.lock
commands/list_clusters.go
vendor/github.com/giantswarm/gsclientgen/v4_cluster_list_item.go

Towards https://github.com/giantswarm/giantswarm/issues/2760. This is successfully tested on `gauss`. 
```
$ gsctl list clusters
ID     ORGANIZATION  NAME                     RELEASE  CREATED
omq8y  giantswarm    Timo: first update test  3.1.1    2018 Mar 07, 13:45 UTC
```

show release version when listing clusters

---

commands/list_releases.go
commands/list_releases_test.go

Ensure that https://github.com/giantswarm/gsctl/issues/181 is fixed
This adds a test that shows the panic is not occuring.
In case the API endpoint is not responding, a user now sees
```
$ gsctl list releases
The API didn't send a response.
Please check your connection using 'gsctl ping'. If your connection is fine,
please try again in a few moments.
```

Fix list releases panic

---

commands/create_kubeconfig.go

This fixes a possible nil pointer exception in `create kubeconfig` where `apiResponse` is not nil, but apiResponse.StatusCode is nil.
```
gsctl --endpoint REDACTED create kubeconfig --cluster REDACTED --certificate-organizations system:masters --auth-token REDACTED
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7611d4]
goroutine 1 [running]:
github.com/giantswarm/gsctl/commands.createKubeconfig(0xc4200a47e0, 0x17, 0x7fffe079634a, 0x24, 0x7fffe079630c, 0x5, 0xc42009e390, 0x2e, 0x0, 0x0, ...)
/go/src/github.com/giantswarm/gsctl/commands/create_kubeconfig.go:366 +0x2f4
github.com/giantswarm/gsctl/commands.createKubeconfigRunOutput(0xaa19a0, 0xc42014e300, 0x0, 0x8) …
```

Fix possible nil pointer dereference in "create kubeconfig"

---

commands/create_cluster.go

This PR makes the `--release` flag visible, which allows to set a specific release version number to use when creating a new cluster.

Reveal --release flag in 'create cluster' command

---

commands/show_cluster.go

The `showClusterActivityName` was `scaleClusterActivityName` in one command

Update show cluster activity name

---

pkce/pkce.go

This lets users know what went wrong if we couldn't get the 'code' from Auth0

Make sure auth0 errors before recieving the code bubble up to the CLI

---

client/client.go

This moves setting of parameters, which is done in all requests so far, into an extra function `setParams`.
Unfortunately not all request functions implement `SetAuthorization(string)`. The `CreateAuthToken` is the exception. So passing the Authorization header still has to be done individually.

Refactor to set request parameters in common way

---

commands/create_cluster_test.go

Addressing comments in https://github.com/giantswarm/gsctl/pull/258#discussion_r203673319

Use defer to safely close mock servers

---

client/client.go
commands/commands.go
commands/login.go
commands/login_giantswarm.go
commands/login_sso.go
commands/root.go
config/config.go
config/config_test.go
config/error.go

This PR introduces my mechanism for being able to run some code on each client run.
Instead of passing it the auth header to use, we pass it a function it can use to get the auth header.
This function will then in the next PR be further developed to check whether or not the token we have
is valid, and if not, it will refresh the token.

Introduce AuthHeaderGetter for eventual Access Token refreshing.

---

commands/show_cluster.go

For https://github.com/giantswarm/giantswarm/issues/3953
As the worker node's local storage cannot be used by end users, for both AWS and Azure, we remove the display of that information from the output of `gsctl show cluster`.

Remove storage from 'gsctl show cluster' output (AWS, Azure)

---

commands/login_giantswarm.go
commands/login_test.go

This PR removes the password from a terminal output of the `gsctl login` command.
In addition, it aligns the color with recent changes, to distinguish verbose output from normal output.

Remove password from verbose output, colorize verbose output

---

commands/login_sso.go
oidc/pkce.go

Towards: https://github.com/giantswarm/giantswarm/issues/4156
This lets gsctl ask for a token with a api specific audience claim.

Wire up the api endpoint to the token request.

---

commands/create_keypair.go
commands/create_kubeconfig.go

As our previously introduced validation doesn't allow for email addresses, this relaxes the validation.

Relax cn prefix validation for key pairs

---

.gitignore
Makefile

This sets the Go version in builds to 1.11.1.
In addition, this sets a `/.cache` volume for the build, to prevent this error:
```
go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache: permission denied
```

Use golang 1.11

---

commands/upgrade_cluster.go

For https://github.com/giantswarm/giantswarm/issues/4553
This ensures that gsctl selects an active release as the target release to upgrade to.

upgrade cluster: ensure the target release is active

---

.circleci/update-homebrew.sh
.circleci/update-scoop.sh

Still aftermath for https://github.com/giantswarm/giantswarm/issues/4810
See also: 
- https://github.com/giantswarm/homebrew-giantswarm/pull/9
- https://github.com/giantswarm/scoop-bucket/pull/2

Fix download URL for homebrew and scoop

---

commands/create_cluster.go
commands/error.go

We discussed this yesterday:
The behaviour is supposed to be, that we only send one worker when creating a cluster - no matter which version it is in.
The API does not currently support this, have we changed our thinking here or is this still valid?

Only send one worker on cluster creation

---

commands/scale_cluster.go

This is really just about saving us an unnecessary api call.

Get the status only when we are sure that it holds useful information

---

commands/show_cluster.go

This modifies the calculation of RAM and CPU totals to use the current worker node count gathered from the cluster status endpoint.
This fixes the problem that a fresh cluster without worker nodes would show totals above zero.
Also the instance type / VM size row is moved further to the top, so that all "static" information is at the top and the dynamic parts are grouped together at the bottom.
```nohighlight
$ ./gsctl show cluster 3eudf
ID:                        3eudf
Name:                      My cluster
Created:                   2019 Feb 01, 10:06 UTC
Organization:              marian
Kubernetes API endpoint:   https://api.3eudf.k8s.gauss.eu-central-1.aws.gigantic.io
Availability Zones:        eu-central-1c
Release version:           6.3.0
Worker EC2 instance type:  m5.xlarge
Worker …
```

Fix calculation of resource totals in 'show cluster'

---

commands/error.go
commands/scale_cluster.go
commands/show_cluster.go

Part of autoscaling changes.
This prevents the error info in the top of the `show cluster` output that occurred when the cluster status endpoint could not yet be accessed.
Here is how it will appear for a cluster after a creation period:
```nohighlight
...
Worker node scaling:       pinned at 0
Worker nodes running:      0
CPU cores in workers:      0
RAM in worker nodes (GB):  0.00
Info: Could not fetch cluster status, so the worker node count displayed might derive from the actual number.
```
Within 20 minutes from creation, an additional line will be shown:
```nohighlight
...
Worker node scaling:       pinned at 0
Worker nodes running:      0
CPU cores in workers:      0
RAM in worker nodes (GB):  0.00
Info: Could not fetch cluster status, so the worker node count displayed might …
```

Prevent error when cluster status endpoint cannot be fetched

---

commands/create_cluster.go
commands/scale_cluster.go

For https://github.com/giantswarm/giantswarm/pull/2206
This fully enables `--num-workers` again in `scale cluster` and `create cluster`.

Revert --num-workers deprecation, update examples

---

cmd/cluster/scale/defaulting/scaling.go
cmd/cluster/scale/defaulting/scaling_test.go

Fixing an issue on Azure where a cluster pinned to 5 nodes is scaled down. The confirmation asks to pin to 0 but should ask to pin to 3. The fix is to always consider `--num-workers`, no matter if AS is enabled or not. 
```
$ gsctl scale cluster mne2v --num-workers 3
Flag --num-workers has been deprecated, Please use --workers-min and --workers-max to specify the node count to use.
The cluster currently has 5 worker nodes running.
Do you want to pin the number of worker nodes to 0? [y/n]: n
command aborted error
```

fix azure scale down

---

commands/upgrade_cluster.go

-c is not a valid option for show cluster
See: 
```
$ gsctl show cluster -c 48d4u
Error: unknown shorthand flag: 'c' in -c
```
vs
```
$ gsctl show cluster -c 48d4u
ID:                        48d4u
...
```
Show Cluster Help Text:
```
$ gsctl show cluster --help
Display details of a cluster
Examples:
gsctl show cluster c7t2o
Usage:
gsctl show cluster [flags]
Flags:
-h, --help   help for cluster
```

Fix the show cluster example inside the cluster upgrade help text

---

capabilities/capabilities.go
capabilities/capabilities_test.go
commands/login/command.go
commands/login/giantswarm_theme.go
commands/login/sso.go
commands/root.go
commands/scale/command_test.go
config/config.go
config/config_test.go
config/error.go

This is supposed to do what https://github.com/giantswarm/gsctl/pull/356 already did, but based on a refactored gsctl code base.
Also fixes client initialization for the `refactor-command-tree` branch.

Add capabilities API and provider awareness, fix client initialization

---

commands/list/command.go
commands/list/nodepools/command.go
commands/list/nodepools/command_test.go

Towards https://github.com/giantswarm/giantswarm/issues/6447, to be merged into https://github.com/giantswarm/gsctl/pull/372
This PR adds the new `gsctl list nodepools <cluster-id>` command to list node pools of a cluster.
```nohighlight
ID     NAME                    AZ     INSTANCE TYPE  NODES MIN/MAX  NODES DESIRED  NODES READY  CPUS  RAM (GB)
6feel  Application servers     A,B,C  p3.2xlarge     3/15           10             9            72    549.0
a7rc4  Batch number crunching  D      p3.8xlarge     2/5            4              4            128   976.0
```
Screenshot

Add 'list nodepools' command

---

Gopkg.lock
Gopkg.toml
commands/list/nodepools/command.go
vendor/github.com/giantswarm/columnize/columnize.go

This PR changes the table output of `gsctl list nodepools` to right-align the numeric columns.

Align numeric columns to the right

---

client/client_test.go
client/clienterror/matcher.go
commands/show/cluster/command.go

This PR enables `gsctl show cluster` as implemented in the `support-v5` branch to work with the older API, not supporting v5 endpoints yet.

Handle malformed response error in 'show cluster' command

---

client/client.go
client/clienterror/clienterror.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/errors/errors.go
commands/errors/handling.go
commands/list/keypairs/command.go
commands/list/nodepools/command.go
commands/list/nodepools/command_test.go
commands/show/command.go
commands/show/nodepool/command.go
commands/show/nodepool/command_test.go
formatting/availability_zones.go
formatting/availability_zones_test.go
formatting/key_pair_id.go
formatting/key_pair_id_test.go
util/certs.go
util/truncate.go
util/truncate_test.go

To be merged into https://github.com/giantswarm/gsctl/pull/372
Part of https://github.com/giantswarm/giantswarm/issues/6447
This PR adds the `gsctl show nodepool <cluster-id>/<nodepool-id>` command.
```nohighlight
$ gsctl show nodepool m0ckd/a7rc4
ID:                    a7rc4
Name:                  Batch number crunching
Node instance type:    p3.8xlarge - 244 GB RAM, 32 CPUs each
Availability zones:    D
Node scaling:          Autoscaling between 2 and 5
Nodes desired:         4
Nodes in state Ready:  4
CPUs:                  128
RAM:                   976 GB
```

Add 'show nodepool' command

---

commands/create/cluster/command.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/delete/cluster/command.go
commands/info/command.go
commands/list/clusters/command.go
commands/list/keypairs/command.go
commands/list/nodepools/command.go
commands/list/organizations/command.go
commands/list/releases/command.go
commands/login/command.go
commands/login/giantswarm_theme.go
commands/logout/command.go
commands/scale/cluster/command.go
commands/show/cluster/command.go
commands/show/nodepool/command.go
commands/show/release/command.go
commands/update/organization/setcredentials/command.go
commands/upgrade/cluster/command.go

Along the lines of https://github.com/giantswarm/gsctl/pull/387 this PR removes the V2 naming from all variables representing the client wrapper.

Rename clientV2 variables to clientWrapper

---

client/client.go
client/client_test.go
commands/login/command.go

This PR removes an outdated naming suffix "V2" stemming from a time where we had two different clients and V2 marked the new one.

Remove v2 naming quirks in client package

---

client/client.go
commands/create/cluster/command.go
commands/create/cluster/command_test.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/delete/cluster/command.go
commands/info/command.go
commands/info/command_test.go
commands/list/clusters/command.go
commands/list/endpoints/command.go
commands/list/keypairs/command.go
commands/list/nodepools/command.go
commands/list/organizations/command.go
commands/list/releases/command.go
commands/logout/command.go
commands/scale/cluster/command.go
commands/show/cluster/command.go
commands/show/nodepool/command.go
commands/show/release/command.go
commands/update/organization/setcredentials/command.go
commands/upgrade/cluster/command.go

This PR is a start to fix authentication issues introduced with recent refactorings.
The problem is that `github.com/giantswarm/gscliauth.config.ChooseScheme(endpoint, token)` always returns the scheme `giantswarm` when a non-empty token is passed via the function's parameters. The token parameter was meant to represent a token provided by the user via the command line, to override any config.
To better reflect, the command structure in this PR now distinguishes between one argument `token` and an additional one named `userProvidedToken`. The latter represents any token provided by the user as a command line argument. The existing `token` can be set based on authentication data from the config.
- Apply the same fix to all other commands.

Fix auth scheme via client initialization

---

.circleci/config.yml
client/client.go
client/clienterror/clienterror.go
client/clienterror/matcher.go
commands/create/cluster/command.go
commands/create/command.go
commands/create/nodepool/command.go
commands/create/nodepool/command_test.go
commands/login/command_test.go
flags/flags.go

Towards https://github.com/giantswarm/giantswarm/issues/6447
This PR adds the `gsctl create nodepool` command.
```
Add a new node pool to a cluster.
This command allows to create a new node pool within a cluster. Node pools
are groups of wortker nodes sharing a common configuration. Create different
node pools to serve workloads with different resource requirements, different
availability zone spreading etc. Node pools are also scaled independently.
Note that some attributes of node pools cannot be changed later. These are:
- ID - will be generated on creation
- Availability zone assignment
- Instance type used
When creating a node pool, all arguments (except for the cluster ID) are
optional. Where an argument is not given, a default will be applied as
follows:
- Name: will be "Unnamed …
```

Add 'create nodepool' command

---

commands/create/cluster/command.go
commands/create/cluster/command_test.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/create/kubeconfig/command_test.go
commands/create/nodepool/command.go
commands/delete/cluster/command.go
commands/info/command.go
commands/list/clusters/command.go
commands/list/endpoints/command.go
commands/list/keypairs/command.go
commands/list/nodepools/command.go
commands/list/organizations/command.go
commands/list/releases/command.go
commands/login/command.go
commands/logout/command.go
commands/ping/command.go
commands/root.go
commands/scale/cluster/command.go
commands/show/cluster/command.go
commands/show/nodepool/command.go
commands/show/release/command.go
commands/update/organization/command.go
commands/update/organization/setcredentials/command.go
commands/upgrade/cluster/command.go
flags/flags.go

This is a cosmetic PR for renaming of attributes of the `flags` package to remove the `Cmd` prefix everywhere.

Rename flags variables to remove `Cmd` prefix

---

Gopkg.lock
Gopkg.toml
commands/create/cluster/command.go
commands/create/cluster/command_test.go
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go

This refactoring PR adds a specific test for the argument collection and validation functions and converts some other tests dealing with YAML parsing into one that into one that is table driven.
This adds a new dependencies that is needed to disable comparison of unexported struct attributes (here: `Arguments.fileSystem`).

Add and refactor tests for 'create cluster'

---

client/client_test.go
client/clienterror/clienterror.go
client/clienterror/matcher.go

Towards https://github.com/giantswarm/giantswarm/issues/4121
This PR adds specific error output for cases where the API server certificate cannot be accepted.
```
$ gsctl list clusters -e https://expired.badssl.com
Certificate is invalid
The certificate has expired (NotBefore: 2015-04-09 00:00:00 +0000 UTC, NotAfter: 2015-04-12 23:59:59 +0000 UTC).
$ gsctl list clusters -e https://wrong.host.badssl.com
Certificate host name mismatch
The certificate host name(s) (*.badssl.com, badssl.com) does not match the URL 'wrong.host.badssl.com'.
$ gsctl list clusters -e https://self-signed.badssl.com
Certificate signed by an unknown authority
The server's certificate has been signed by 'CN=*.badssl.com,O=BadSSL,L=San Francisco,ST=California,C=US'.
```
There are more cases considered in the code …

Provide better feedback in case of TLS certificate problems

---

commands/show/cluster/command.go

This PR adds user-friendly error output in the case that the cluster could not be found via v5 nor v4  detail endpoints. Without this change, there is no output and gsctl exits with status 0 in this case.
```
$ gsctl show cluster dfdg -v
Fetching details for cluster dfdg.
Fetching details for cluster via v5 API endpoint.
No usable v5 response. Fetching details for cluster via v4 API endpoint.
Cluster not found
Either there is no cluster with ID 'dfdg', or you have no access to it.
Please check whether the cluster is listed when executing 'gsctl list clusters'.
```

'gsctl show cluster': Add handling for cluster not found error

---

commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/create/kubeconfig/command_test.go

Towards https://github.com/giantswarm/giantswarm/issues/6447, https://github.com/giantswarm/giantswarm/issues/5465
This PR changes the behaviour if the `gsctl create kubeconfig` command
- to support v5 clusters, as it attempts to fetch v5 cluster details for the given cluster ID first, then only attempts v4 if that failed.
- some output regarding the crteated files is only printed when the `-v`/`--verbose` flag is applied, to make the output cleaner.

Adapt 'gsctl create kubeconfig' to add support for v5 clusters

---

commands/list/releases/command.go

This fixes a bug where output would be printed repeatedly, likely introduced with the latest change in this command.

Fix new output bug in 'list releases'

---

commands/show/cluster/command.go

Implements what https://github.com/giantswarm/gsctl/pull/449 did for the `gsctl show cluster` command. This enables the command to work again on Azure and KVM.
```
gsctl show cluster 35ac3 -e gollum -v
Fetching details for cluster 35ac3.
Fetching details for cluster via v5 API endpoint.
[GET /v5/clusters/{cluster_id}/][400] getClusterV5 default  &{Code:NOT_SUPPORTED Message:The endpoint is not implemented for this provider. (not supported error)}
```
```
gsctl show cluster 35ac3 -e gollum -v
Fetching details for cluster 35ac3.
Fetching details for cluster via v5 API endpoint.
No usable v5 response. Fetching details for cluster via v4 API endpoint.
Fetching status for v4 cluster.
ID:                        35ac3
Name:                      Giant Swarm Frontend Cluster
Created: …
```

Fix v5 -> v4 fall back in gsctl show cluster

---

commands/create/nodepool/command.go

For https://github.com/giantswarm/giantswarm/issues/6447
This updates the usage info regarding default values.
Depends on https://github.com/giantswarm/api/pull/923

Update usage info regarding defaults in 'create nodepool'

---

go.mod
go.sum

GitHub rewrites the commit when merging through the UI which gives it a
new ID. Update the dependency to reference the commit ID on master branch of
gsclientgen.

Update gsclientgen commit ref

---

client/clienterror/clienterror.go
client/error.go
commands/create/cluster/command.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/create/nodepool/command.go
commands/delete/cluster/command.go
commands/delete/nodepool/command.go
commands/info/command.go
commands/list/clusters/command.go
commands/list/keypairs/command.go
commands/list/nodepools/command.go
commands/list/organizations/command.go
commands/list/releases/command.go
commands/login/command.go
commands/logout/command.go
commands/scale/cluster/command.go
commands/show/cluster/command.go
commands/show/nodepool/command.go
commands/show/release/command.go
commands/update/cluster/command.go
commands/update/nodepool/command.go
commands/update/organization/setcredentials/command.go
commands/upgrade/cluster/command.go

This PR aligns the handling of Internal Server Errors (HTTP 500) in all commands.
- In the `clienterror` package we make sure the error "message" part is passed to the returned APIError object.
- In the `client.HandleErrors()` function we make sure to handle the internal error
- We apply `client.HandleErrors()` consistently in every command.
```
gsctl scale cluster ...
[GET /v4/clusters/{cluster_id}/][500] getCluster default  &{Code:INTERNAL_ERROR Message:Something bad happened which we'll explain somewhere else.}
```
```
gsctl scale cluster ...
An internal error occurred.
Something bad happened which we'll explain somewhere else.
```

Handle error 500 consistently in all commands

---

commands/create/cluster/command.go

This fixes the false statement that by default the cluster would have no node pools.

Fix usage info in 'create cluster' command

---

commands/list/clusters/command.go

Towards https://github.com/giantswarm/giantswarm/issues/7516
This ensures an output for `gsctl list clusters` when there are clusters being deleted, but no active clusters.

Fix 'No clusters' output when clusters are being deleted

---

commands/errors/errors.go
commands/show/nodepool/command.go
commands/show/nodepool/command_test.go

If a user would give an arbitrary argument not containing a `/` separator to the `gsctl show nodepool` command, a panic would occur.
Towards https://github.com/giantswarm/giantswarm/issues/6447

Improve handling of positional argument in 'gsctl show nodepool' command

---

capabilities/service_test.go
client/client.go
commands/scale/cluster/command.go
commands/update/cluster/command.go
commands/upgrade/cluster/command.go
commands/upgrade/cluster/command_test.go

For https://github.com/giantswarm/giantswarm/issues/6447
This enables support for v5 clusters to the `gsctl upgrade cluster` command.
Also contains a bugfix: Make use of the `--force` flag that didn't have any effect previously.
```
$ ./gsctl show cluster 87bcq
Cluster ID:                87bcq
Name:                      marian upgrade v5 test
Created:                   2019 Nov 26, 11:22 UTC
Organization:              nodepools
Kubernetes API endpoint:   https://api.87bcq.k8s.gauss.eu-central-1.aws.gigantic.io
Master availability zone:  eu-central-1a
Release version:           10.0.0
$ ./gsctl upgrade cluster 87bcq
Cluster '87bcq' will be upgraded from version 10.0.0 to 10.0.1.
Changelog:
- cloudformation: Add IAMManager IAM role for kiam managed app.
- cloudformation: Add Route53Manager …
```

Add v5 support to 'gsctl upgrade cluster'

---

commands/scale/cluster/command.go

Fixes https://github.com/giantswarm/giantswarm/issues/7754
In `gsctl scale cluster` the client was misconfigured.
This revealed a larger problem to be solved in gsctl as a whole, which is not covered in this PR.

Pass user provided token (usually empty) instead of token

---

commands/show/cluster/command.go

For https://github.com/giantswarm/giantswarm/issues/6447
This PR adds more output to the `gsctl show cluster` command in case it is a v5 (node pools) cluster which is supposed to guide users to the commands giving them more information (or for creating a new node pool if there are none).
Before:
After:

'gsctl show cluster': add some guidance for node pools clusters

---

commands/create/kubeconfig/command.go

Updates the URL we use to explain where to get kubectl.

Update kubectl installation docs URL

---

.circleci/config.yml

The goal of this PR is to make release automation on tag pushes work again.
In PR https://github.com/giantswarm/gsctl/pull/459 I modified the regex and removed/forgot the slashes in the beginning and the end. This could be the reason why it's not working at all.

Attempt to fix release automation regex

---

.circleci/config.yml
Makefile

Previously the `make prebuild` target failed in CI with this error:
failed to initialize build cache at /.cache/go-build: mkdir /.cache/go-build: permission denied
Here is the attempt to fix this.

Fix release automation - 'make prebuild' 

---

commands/scale/cluster/command.go

Apparently I was testing the wrong thing manually. It actually needs to match against a bad request error to work. 
Example here: https://github.com/giantswarm/gsctl/blob/11c2ebd40ad6c38a8fe0932ef4be2e206a58f879/commands/create/kubeconfig/command.go#L375

Actually check for bad request instead of not supported

---

docs/Release.md

- Moves prerequisites to the bottom, as they are normally met in CI.
- Improves the sub-headlines.

Improve readability of release docs

---

client/client.go
go.mod
go.sum

Following from https://github.com/giantswarm/gsclientgen/pull/54 and towards https://github.com/giantswarm/giantswarm/issues/8347
`gsctl` missed the versioned apps changes in https://github.com/giantswarm/api-spec/pull/192 so it needs to be updated with a newly generated `gsclientgen`.
As far as I can tell, these functions are here for https://github.com/giantswarm/giantswarm/issues/7033 but they're not really used yet so I think this change won't affect anything.

Update apps to use v4

---

commands/info/command.go

This PR fixes and improves the printing of relevant environment variables in `gsctl info`.
1. Environment variables are now also printed if API access fails. (In this case it's actually most important!)
2. We also show the relevant environment variables `HTTPS_PROXY` and `NO_PROXY`.
3. We show the variables if set, even if the value is an empty string. Before they would only be shown if non-empty.
gsctl's HTTP client is configured using Go's [`net/http.ProxyFromEnvironment`](https://golang.org/pkg/net/http/#ProxyFromEnvironment) function. This means the proxy behaviour is influenced by the environment variables
- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY
So far we listed only showed the first of the three in the `gsctl info` command, and only in the case that the API call to the info endpoint …

Improve 'gsctl info' printing of environment variables

---

commands/show/cluster/command.go
commands/show/cluster/command_test.go

This changes the labels placeholder from `-` to `n/a`.
Before:
After:

In 'gsctl show cluster', use "n/a" placeholder when cluster has no labels

---

client/clienterror/clienterror.go
commands/scale/cluster/command.go

As seen in https://gigantic.slack.com/archives/CQ465CFG8/p1591177330001300
The `--num-workers` flag was not actually working for the 'scale cluster' command. It is now 👍 
Also, this fixes:
* There was a hard-coded error in the client that would always display the `The cluster could not be updated. workers-min and workers-max must be equal without autoscaling.` error whenever there was an `INVALID_INPUT` error code coming from the modify cluster response.
* If you wanted to downscale a cluster, the confirmation would not display the actual worker node counts in the scale request.

Fix not being able to use the '--num-workers' flag for scaling clusters

---

commands/update/cluster/command.go

Towards https://github.com/giantswarm/giantswarm/issues/12555
This PR adds a small disclaimer that `HA masters` are only supported on AWS

azure v5: mention that HA masters is not supported

---

commands/list/clusters/command.go
commands/list/clusters/command_test.go

Fixes https://github.com/giantswarm/giantswarm/issues/12838
Returns `[]` instead of `null` for empty cluster list in `gsctl list clusters`

return [] for empty cluster list

---

commands/create/nodepool/command.go
commands/create/nodepool/command_test.go
commands/create/nodepool/error.go

Towards https://github.com/giantswarm/giantswarm/issues/12860
This PR allows setting the number of AZs to `-1`.
<details>
<summary>Trying to use the '-1' value on Azure</summary>
</details>

azure v5: add support for null NP AZs

---

commands/list/nodepools/command.go

As seen on https://gigantic.slack.com/archives/CNUDS3AMU/p1598437605023500
We already had something like this for the `show nodepool` command, but not here.

azure v5: NP lister: show placeholder for unknown VM sizes/instance types

---

commands/root.go
flags/flags.go
go.mod
go.sum

Towards giantswarm/giantswarm#12975
Requires https://github.com/giantswarm/gscliauth/pull/25
This PR adds a `--silence-http-endpoint-warnings` flag which disables `Warning: endpoint URL uses an insecure protocol` messages printed when using gsctl with a http endpoint.

add --silence-http-endpoint-warning flag

---

.circleci/config.yml
Makefile
docs/Release.md
go.mod

This PR updates gsctl to be compiled with go 1.15.1

Use go 1.15.1 + clarify Release process

---

Makefile

Apparently the `-stretch` image of go 1.15 does not exist on the docker hub. This PR switches to the `-buster` image for creating release binaries.

Use buster golang image for releases in Makefile

---

commands/update/nodepool/command.go
commands/update/nodepool/command_test.go

This validates that the node pool is actually changed before trying to send an update request. If it isn't updated, it throws this error:

Validate if node pool is actually changed before trying to update it

---

commands/show/cluster/command.go
commands/show/cluster/command_test.go
commands/show/cluster/error.go

Looks like we missed this somehow.
This adds support for printing node pool stats (such as total memory in nodes, or total CPUs in nodes) when viewing cluster details for a cluster (`gsctl show cluster <id>`)

azure v5: add support for showing NP stats in the cluster details

---

commands/create/nodepool/command.go

azure v5: change example node pool vm size to 'Standard_D4s_v3'

---

commands/upgrade/cluster/command.go
pkg/releaseinfo/releaseinfo_test.go

As seen on https://gigantic.slack.com/archives/CNUDS3AMU/p1605091559107400
Currently, if the V5 cluster upgrade fails (or is blocked by an admission controller), the app doesn't actually throw an error. With this PR, it does.

Actually throw the error if v5 cluster upgrade fails

---

commands/create/cluster/command.go
commands/create/cluster/command_test.go
commands/create/cluster/read_definition_test.go
commands/create/cluster/v5.go
commands/types/types.go

Towards https://github.com/giantswarm/giantswarm/issues/14617
This PR makes use of the new master nodes fields in the cluster creation request:
* now on Azure, if there are no supported AZs in the installation, we set the new `AvailabilityZonesUnspecified` field to `true` - works great on `germanywestcentral` 👍🏻 
* if the `--create-default-nodepool` is set to `true`, and the cluster was created with no AZs, then the nodepool is also created with no AZs

Use new master nodes properties

---

README.md
capabilities/capabilities.go
capabilities/service.go
commands/create/kubeconfig/command.go
commands/types/types.go
flags/flags.go

Towards https://github.com/giantswarm/giantswarm/issues/14961
Most changes in this PR are only comments, however one command is affected:
- The `gsctl create kubeconfig` command offers the `--tenant-internal` flag, which is deprecated in favor of `--internal-api`.

Terminology change: "tenant cluster" to "workload cluster"

---

nodespec/azure.go

Towards: https://github.com/giantswarm/giantswarm/issues/15731
Removed unusable VM sizes

removed small azure vm sizes

---

commands/create/kubeconfig/command.go

Closes https://github.com/giantswarm/giantswarm/issues/15957
This ensures that when `--kubie` is set, the necessary edits are made to the kubectl config.

create kubeconfig: Update config file when --kubie is set

---

commands/create/cluster/command.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/create/nodepool/command.go
commands/list/clusters/command.go
commands/list/nodepools/command.go
commands/list/releases/command.go

Towards https://github.com/giantswarm/giantswarm/issues/17907.
This PR adds deprecation notices to the following commands:
`gsctl create keypair`
`gsctl create kubeconfig`
`gsctl list nodepools`
It also updates the existing deprecation notices by fixing a small typo and aligning the replacement `kubectl gs` commands suggested.

Add deprecation notices to `create keypair`, `create kubeconfig`, and `list nodepools` commands

---

commands/create/cluster/command.go
commands/create/keypair/command.go
commands/create/kubeconfig/command.go
commands/create/nodepool/command.go
commands/list/clusters/command.go
commands/list/nodepools/command.go
commands/list/releases/command.go
util/deprecated.go
util/deprecated_test.go

Closes https://github.com/giantswarm/roadmap/issues/765.
We currently display deprecation notices for `gsctl` commands that have a direct `kubectl gs` replacement. However, `kubectl gs` does not work for KVM installations, and so we should not show the deprecation notices there.
This PR adds a check for the installation's provider before displaying a command as deprecated. It also aligns the spelling of the word "favor" to use the American spelling.
An example of the deprecation notice shown:

Avoid printing deprecation notices on KVM

---

.circleci/config.yml
Makefile
go.mod
go.sum

Goal of this PR is to replace `github.com/dgrijalva/jwt-go` with `github.com/golang-jwt/jwt/v4` for security reasons.
In order to be able to build again, we are updating the CircleCI configuration for Go 1.17.

Update important dependencies and Go version

---

commands/show/cluster/command.go
commands/show/nodepool/command.go
commands/show/release/command.go
commands/show/release/command_test.go

Towards https://github.com/giantswarm/giantswarm/issues/22453.
This PR adds deprecation notices to the `show cluster`, `show nodepool`, and `show release` commands. Similar to the notices for the `list RESOURCES` commands, these notices will only be shown for non-KVM installations.
Example for the `show cluster` command:
The equivalent `kubectl-gs` commands are sourced from our [gsctl migration docs](https://docs.giantswarm.io/ui-api/gsctl/migrate/).

Add deprecation notices to `show RESOURCE` commands

---

.circleci/config.yml
README.md

This PR updates the README to
- Remove the coveralls badge
- Make it clear that gsctl is a deprecated part of our product

Update gsctl README, remove coveralls call
